; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "DatenJäger, Sistema de Gestion Documental"
#define MyAppVersion "Alpha V1. Launch Test"
#define MyAppPublisher "RavenCorp"
#define MyAppURL "https://github.com/RavenCore99/DatenJ-ger.git"
#define MyAppExeName "MyProg-x64.exe"
#define MyAppAssocName "DatenJäger"
#define MyAppAssocExt ".exe"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E667AB69-F480-40BF-8A7C-6622079EF273}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=/home/raven/OneDrive/UDEC/VIII Semestre/Proyecto/Lauch Test (64bits)\DatenJäger
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DefaultGroupName=DatenJäger
InfoAfterFile=Z:\home\raven\OneDrive\UDEC\VIII Semestre\Proyecto\Lauch Test (64bits)\V.2\README.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=Z:\home\raven\OneDrive\UDEC\VIII Semestre\Proyecto\Setup
OutputBaseFilename=Setup
SetupIconFile=Z:\home\raven\OneDrive\UDEC\VIII Semestre\Proyecto\Lauch Test (64bits)\V.2\logo.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Program Files (x86)\Inno Setup 6\Examples\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\raven\OneDrive\UDEC\VIII Semestre\Proyecto\Lauch Test (64bits)\V.2\base_datos_pdfs.db"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\raven\OneDrive\UDEC\VIII Semestre\Proyecto\Lauch Test (64bits)\V.2\DatenJäger_64bit.spec"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\raven\OneDrive\UDEC\VIII Semestre\Proyecto\Lauch Test (64bits)\V.2\GestorPDFs.spec"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\raven\OneDrive\UDEC\VIII Semestre\Proyecto\Lauch Test (64bits)\V.2\logo.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\raven\OneDrive\UDEC\VIII Semestre\Proyecto\Lauch Test (64bits)\V.2\logo.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\raven\OneDrive\UDEC\VIII Semestre\Proyecto\Lauch Test (64bits)\V.2\README.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\raven\OneDrive\UDEC\VIII Semestre\Proyecto\Lauch Test (64bits)\V.2\README.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\raven\OneDrive\UDEC\VIII Semestre\Proyecto\Lauch Test (64bits)\V.2\v10_v4.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "Z:\home\raven\OneDrive\UDEC\VIII Semestre\Proyecto\Lauch Test (64bits)\V.2\VC_redist.x64.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

